# -*- coding: utf-8 -*-
"""navigation3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tq9hp_D-Z71fwzuF7UoJIznYt_wWa0S6
"""

from std_srvs.srv import Empty, EmptyResponse
import rospy
import time

def go_home(request):
    rospy.loginfo("Going to home.")
    rospy.sleep(2)
    rospy.loginfo("Arrived.")
    return EmptyResponse()

def go_to_kitchen(request):
    rospy.loginfo("Going to kitchen.")
    rospy.sleep(2)
    rospy.loginfo("Arrived.")
    return EmptyResponse()
    
def stop(request):
    rospy.loginfo("Stop!")
    return EmptyResponse()

if __name__ == "__main__":
    rospy.Service("/go_home", Empty, go_home)
    rospy.Service("/go_to_kitchen", Empty, go_to_kitchen)
    rospy.Service("/stop", Empty, stop)